const data = [
    {
        id: '01',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Onboarding Access",
    },
    {
        id: '02',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Google Search Console Access",
    },
    {
        id: '03',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Google Anlytics Access",
    },
    {
        id: '04',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Website Access",
    },
    {
        id: '05',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Technical Audit",
    },
    {
        id: '06',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Anchor Text in Semantic Analysis",
    },
    {
        id: '07',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Competitor Analysis",
    },
    {
        id: '08',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Anchor Text/URL Mapping",
    },
    {
        id: '09',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Google Data Studio Report+Local Reporting Suite",
    },
    {
        id: '10',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Site Lavel Optimization",
    },
    {
        id: '11',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "On Page Optimization",
    },
    {
        id: '12',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Content Creation",
    },
    {
        id: '13',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Content Publishing",
    },
    {
        id: '14',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Premium Press Release",
    },
    {
        id: '15',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Authority Niche Placements",
    },
    {
        id: '16',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Review Management",
    },
    {
        id: '17',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Index Links",
    },
    {
        id: '18',
        cell1: "",
        cell2: "",
        cell3: "",
        cell4: "",
        cell5: "",
        cell6: "",
        name: "Video Recap",
    },
]
export default data